### ISSUE TITLE
Notice: Undefined index: weight in Drupal\Core\Entity\EntityDisplayBase->init()

### ISSUE THREAD

**Issue by Ohmdesbois** [phase2/octane#1]
In a fresh install :

Notice: Undefined index: weight in Drupal\Core\Entity\EntityDisplayBase->init() (line 166 of core/lib/Drupal/Core/Entity/EntityDisplayBase.php).

Drupal\Core\Entity\EntityDisplayBase->init() (Line: 143)
Drupal\Core\Entity\EntityDisplayBase->__construct(Array, 'entity_form_display') (Line: 126)
Drupal\Core\Entity\Entity\EntityFormDisplay->__construct(Array, 'entity_form_display') (Line: 224)
Drupal\Core\Config\Entity\ConfigEntityStorage->doCreate(Array) (Line: 184)
Drupal\Core\Entity\EntityStorageBase->create(Array) (Line: 509)
Drupal\Core\Entity\Entity::create(Array) (Line: 42)
lightning_media_media_bundle_insert(Object)
call_user_func_array('lightning_media_media_bundle_insert', Array) (Line: 402)
Drupal\Core\Extension\ModuleHandler->invokeAll('media_bundle_insert', Array) (Line: 369)
Drupal\Core\Config\Entity\ConfigEntityStorage->invokeHook('insert', Object) (Line: 470)
Drupal\Core\Entity\EntityStorageBase->doPostSave(Object, ) (Line: 395)
Drupal\Core\Entity\EntityStorageBase->save(Object) (Line: 259)
Drupal\Core\Config\Entity\ConfigEntityStorage->save(Object) (Line: 358)
Drupal\Core\Entity\Entity->save() (Line: 637)
Drupal\Core\Config\Entity\ConfigEntityBase->save() (Line: 329)
Drupal\Core\Config\ConfigInstaller->createConfiguration('', Array) (Line: 133)
Drupal\Core\Config\ConfigInstaller->installDefaultConfig('module', 'lightning_media_instagram') (Line: 75)
Drupal\Core\ProxyClass\Config\ConfigInstaller->installDefaultConfig('module', 'lightning_media_instagram') (Line: 248)
Drupal\Core\Extension\ModuleInstaller->install(Array, 1) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array) (Line: 79)
lightning_extensions_enable(Array, Object)
call_user_func_array('lightning_extensions_enable', Array) (Line: 111)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 51)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 583)
Drupal\Core\Form\FormBuilder->processForm('install_configure_form', Array, Object) (Line: 314)
Drupal\Core\Form\FormBuilder->buildForm('Drupal\Core\Installer\Form\SiteConfigureForm', Object) (Line: 884)
install_get_form('Drupal\Core\Installer\Form\SiteConfigureForm', Array) (Line: 574)
install_run_task(Array, Array) (Line: 530)
install_run_tasks(Array) (Line: 115)
install_drupal(Object) (Line: 39)

**Comment by mike-potter** [comment]
This project is still in early development and is not functional yet.
