### ISSUE TITLE
Patch failed to apply

### ISSUE THREAD

**Issue by crittermike** [phase2/octane#15]
After running `composer create-project phase2/octane:8.6.0-alpha3 PROJECTNAME`, I see this in the output:

> Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2018-07-25/2988162-3.patch

**Comment by jhedstrom** [comment]
What's weird is that node doesn't appear to exist: https://www.drupal.org/node//2988162

Can you run with `--verbose` enabled and that should indicate which module/project is attempting to patch itself...

**Comment by jhedstrom** [comment]
Oops, I had a typo in the url above. It is an actual issue https://www.drupal.org/node/2988162
